"""
Financial Analysis Engine.

Combines all deterministic financial calculations into a
single structured analysis.
"""

from __future__ import annotations

from dataclasses import dataclass

from .growth import growth_rate
from .models import FinancialStatement
from .ratios import (
    current_ratio,
    debt_to_ebitda,
    ebitda_margin,
    net_margin,
    return_on_assets,
    return_on_equity,
)


@dataclass(slots=True, frozen=True)
class FinancialAnalysisReport:
    """
    Output generated by the Financial Analysis Engine.
    """

    current_ratio: float

    ebitda_margin: float

    net_margin: float

    roa: float

    roe: float

    debt_to_ebitda: float

    revenue_growth: float

    ebitda_growth: float

    earnings_growth: float


class FinancialAnalysisEngine:
    """
    Runs all financial calculations on a company.

    This class serves as the public API for the
    financial engine.
    """

    def analyze(
        self,
        *,
        current: FinancialStatement,
        previous: FinancialStatement,
    ) -> FinancialAnalysisReport:

        return FinancialAnalysisReport(
            current_ratio=current_ratio(
                current.current_assets,
                current.current_liabilities,
            ),
            ebitda_margin=ebitda_margin(
                current.revenue,
                current.ebitda,
            ),
            net_margin=net_margin(
                current.revenue,
                current.net_income,
            ),
            roa=return_on_assets(
                current.net_income,
                current.total_assets,
            ),
            roe=return_on_equity(
                current.net_income,
                current.shareholders_equity,
            ),
            debt_to_ebitda=debt_to_ebitda(
                current.total_debt,
                current.ebitda,
            ),
            revenue_growth=growth_rate(
                previous.revenue,
                current.revenue,
            ),
            ebitda_growth=growth_rate(
                previous.ebitda,
                current.ebitda,
            ),
            earnings_growth=growth_rate(
                previous.net_income,
                current.net_income,
            ),
        )
